### GET 请求参数处理演示, 发送全部参数
GET http://localhost:8080/demo/getparam?username=Tom&password=1234&goto=123
Accept: application/json

### GET 请求参数处理演示，不发送可选参数 username
GET http://localhost:8080/demo/getparam?password=1234&goto=123
Accept: application/json

### GET 请求参数处理演示，不发送必须参数 password，会发生异常: Required String parameter 'password' is not present
GET http://localhost:8080/demo/getparam?goto=123
Accept: application/json

### POST 请求参数处理演示
POST http://localhost:8080/demo/postparam
Content-Type: application/x-www-form-urlencoded

username=Jerry&password=111&goto=beijing

### POST 请求测试可选参数 username
POST http://localhost:8080/demo/postparam
Content-Type: application/x-www-form-urlencoded

password=111&goto=beijing

### POST 请求测试必须参数 password， 服务器出现错误：Required String parameter 'password' is not present
POST http://localhost:8080/demo/postparam
Content-Type: application/x-www-form-urlencoded

goto=beijing

### 测试，从请求路径中映射变量
GET http://localhost:8080/demo/users/5
Accept: application/json

### 测试， 利用请求路径传递两个变量
GET http://localhost:8080/demo/user/18/item/102
Accept: application/json

### POST 请求发送JSON 数据, 服务器可以使用 @RequestBody 接收
POST http://localhost:8080/demo/register
Content-Type: application/json

{
  "id": 12,
  "username": "Andy",
  "password": "123abc",
  "roles": "ADMIN"
}

### 测试Excel下载：
GET http://localhost:8080/demo/excel







